[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

solc = "0.8.31"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true

[rpc_endpoints]
tenderly = "${TENDERLY_RPC}"
mainnet = "${ETH_RPC_URL}"

[fmt]
bracket_spacing = true
line_length = 100
tab_width = 4
